export {
  defineEmulator,
  validateEmulatorPlugin,
  validateEmulatorSessionCapabilities,
} from './emulator.js';
export type {
  EmulatorAudioFrame,
  EmulatorCapabilities,
  EmulatorCartridgeSave,
  EmulatorCoreDefinition,
  EmulatorInput,
  EmulatorOperationFailure,
  EmulatorOperationResult,
  EmulatorOperationSuccess,
  EmulatorPluginDefinition,
  EmulatorRom,
  EmulatorSaveState,
  EmulatorSaveStateResult,
  EmulatorSaveStateSuccess,
  EmulatorSession,
  EmulatorSessionStatus,
  EmulatorStopResult,
  EmulatorStopSuccess,
  EmulatorVideoFrame,
  UnsubscribeEmulatorOutput,
} from './emulator.js';
