import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

export const SUPPORTED_LOCALES = ['en-US', 'pt-BR', 'zh-CN'] as const;
export type SupportedLocale = (typeof SUPPORTED_LOCALES)[number];

export const resolveLocale = (
  preferred: string | undefined,
  systemLocale: string,
): SupportedLocale => {
  const normalized = (preferred ?? systemLocale).toLowerCase();
  if (normalized === 'pt' || normalized.startsWith('pt-br')) return 'pt-BR';
  if (normalized === 'zh-cn' || normalized === 'zh-sg' || normalized.startsWith('zh-hans'))
    return 'zh-CN';
  if (normalized === 'en' || normalized.startsWith('en-')) return 'en-US';
  return 'en-US';
};

const en = {
  translation: {
    addGame: 'Add game',
    allGames: 'All games',
    archive: 'Archive',
    artwork: 'Artwork',
    backLibrary: 'Back to library',
    backSystems: 'Systems',
    consoleAction: 'console action',
    chooseSystem: 'Choose your system',
    available: 'Available',
    comingSoon: 'Coming soon',
    close: 'Close',
    connected: 'Connected',
    confirmSystem: 'Enter system',
    formats: 'Formats',
    generationEightBit: '8-bit home generation',
    generationHandheld: 'Handheld generation',
    generationSixteenBit: '16-bit home generation',
    generationThreeD: 'Early 3D generation',
    disconnected: 'Disconnected device',
    emptyAction: 'Choose a local ROM',
    emptyBody: 'Add your own .gb or .gbc files. Your library stays private on this computer.',
    emptyTitle: 'Your archive is ready',
    errorTitle: 'Something interrupted the flow',
    favorites: 'Favorites',
    favoriteGame: 'Favorite',
    feedbackSounds: 'Feedback sounds',
    gameControls: 'Game controls',
    importError: 'The game could not be imported.',
    inputSettings: 'Input settings',
    mappingAssigned: 'Assigned',
    mappingCancelled: 'Change cancelled.',
    mappingCancel: 'Cancel',
    mappingConfirm: 'Confirm',
    mappingChooseDevice: 'Choose a device, then confirm to configure its buttons.',
    mappingEditButton: 'Choose a console button and confirm to edit.',
    mappingPreview: 'Input captured. Confirm to save or go back to cancel.',
    mappingPressInput: 'Press a key or controller button.',
    mappingSaved: 'Mapping saved.',
    interfaceAudio: 'Interface audio',
    interfaceLanguage: 'Interface language',
    language: 'Language',
    library: 'Library',
    emptyCategory: 'Nothing here yet',
    loading: 'Restoring your archive…',
    localPrivate: 'Original local file · Private by design',
    muteUiSounds: 'Mute interface sounds',
    muted: 'Muted',
    nowPlaying: 'Now playing',
    nextSystem: 'Next system',
    pause: 'Pause',
    play: 'Play now',
    playerOneDevice: 'Player one device',
    ready: 'Ready',
    readyToPlay: 'Ready to play',
    previousSystem: 'Previous system',
    recent: 'Recently played',
    removeFavorite: 'Remove favorite',
    resume: 'Resume',
    saveStates: 'Save states',
    saveSlot: 'Slot {{number}}',
    emptySlot: 'Empty',
    saveState: 'Save',
    loadState: 'Load',
    search: 'Search your library',
    sessionReady: 'Ready when you are',
    exitApplication: 'Exit PixelCore',
    continuePlaying: 'Continue playing',
    exitQuestion: 'Leave this game?',
    exitToLibrary: 'Exit to library',
    settings: 'Settings',
    settingsAdjustHint: 'Adjust',
    settingsCloseHint: 'Back',
    settingsConfirmHint: 'Confirm',
    settingsMoveHint: 'Navigate',
    soundsOn: 'On',
    playHint: 'Confirm again to play',
    globalSettings: 'PixelCore settings',
    systemPosition: '{{current}} of {{total}}',
    systems: 'Choose system',
    unavailableSystem: '{{name}} is coming soon.',
    statusPaused: 'Paused',
    statusRunning: 'Session running',
    statusStarting: 'Starting',
    stop: 'Exit game',
    tryAgain: 'Try again',
    preferencesWarningTitle: 'Preferences not saved',
    preferencesWarningMessage: 'Your changes remain active, but could not be stored.',
    volume: 'Volume',
  },
};
const pt = {
  translation: {
    addGame: 'Adicionar jogo',
    allGames: 'Todos os jogos',
    archive: 'Arquivo',
    artwork: 'Capa',
    backLibrary: 'Voltar à biblioteca',
    backSystems: 'Consoles',
    consoleAction: 'ação do console',
    chooseSystem: 'Escolha seu console',
    available: 'Disponível',
    comingSoon: 'Em breve',
    close: 'Fechar',
    connected: 'Conectado',
    confirmSystem: 'Entrar no console',
    formats: 'Formatos',
    generationEightBit: 'Geração doméstica 8-bit',
    generationHandheld: 'Geração portátil',
    generationSixteenBit: 'Geração doméstica 16-bit',
    generationThreeD: 'Primeira geração 3D',
    disconnected: 'Dispositivo desconectado',
    emptyAction: 'Escolher uma ROM local',
    emptyBody:
      'Adicione seus arquivos .gb ou .gbc. Sua biblioteca permanece privada neste computador.',
    emptyTitle: 'Seu arquivo está pronto',
    errorTitle: 'Algo interrompeu o fluxo',
    favorites: 'Favoritos',
    favoriteGame: 'Favoritar',
    feedbackSounds: 'Sons de feedback',
    gameControls: 'Controles do jogo',
    importError: 'Não foi possível importar o jogo.',
    inputSettings: 'Configurações de controle',
    mappingAssigned: 'Atribuído',
    mappingCancelled: 'Alteração cancelada.',
    mappingCancel: 'Cancelar',
    mappingConfirm: 'Confirmar',
    mappingChooseDevice: 'Escolha um dispositivo e confirme para configurar os botões.',
    mappingEditButton: 'Escolha um botão do console e confirme para editar.',
    mappingPreview: 'Entrada capturada. Confirme para salvar ou volte para cancelar.',
    mappingPressInput: 'Pressione uma tecla ou botão do controle.',
    mappingSaved: 'Mapeamento salvo.',
    interfaceAudio: 'Áudio da interface',
    interfaceLanguage: 'Idioma da interface',
    language: 'Idioma',
    library: 'Biblioteca',
    emptyCategory: 'Nada por aqui ainda',
    loading: 'Restaurando seu arquivo…',
    localPrivate: 'Arquivo local original · Privado por design',
    muteUiSounds: 'Silenciar sons da interface',
    muted: 'Silenciado',
    nowPlaying: 'Jogando agora',
    nextSystem: 'Próximo console',
    pause: 'Pausar',
    play: 'Jogar agora',
    playerOneDevice: 'Dispositivo do jogador 1',
    ready: 'Pronto',
    readyToPlay: 'Pronto para jogar',
    previousSystem: 'Console anterior',
    recent: 'Jogados recentemente',
    removeFavorite: 'Remover favorito',
    resume: 'Continuar',
    saveStates: 'Estados salvos',
    saveSlot: 'Slot {{number}}',
    emptySlot: 'Vazio',
    saveState: 'Salvar',
    loadState: 'Carregar',
    search: 'Buscar na biblioteca',
    sessionReady: 'Tudo pronto para jogar',
    exitApplication: 'Sair do PixelCore',
    continuePlaying: 'Continuar jogando',
    exitQuestion: 'Sair deste jogo?',
    exitToLibrary: 'Sair para a biblioteca',
    settings: 'Configurações',
    settingsAdjustHint: 'Ajustar',
    settingsCloseHint: 'Voltar',
    settingsConfirmHint: 'Confirmar',
    settingsMoveHint: 'Navegar',
    soundsOn: 'Ligado',
    playHint: 'Confirme novamente para jogar',
    globalSettings: 'Configurações do PixelCore',
    systemPosition: '{{current}} de {{total}}',
    systems: 'Escolher console',
    unavailableSystem: '{{name}} estará disponível em breve.',
    statusPaused: 'Pausado',
    statusRunning: 'Sessão em andamento',
    statusStarting: 'Iniciando',
    stop: 'Sair do jogo',
    tryAgain: 'Tentar novamente',
    preferencesWarningTitle: 'Preferências não salvas',
    preferencesWarningMessage: 'As alterações continuam ativas, mas não puderam ser salvas.',
    volume: 'Volume',
  },
};
const zh = {
  translation: {
    addGame: '添加游戏',
    allGames: '所有游戏',
    archive: '档案',
    artwork: '封面',
    backLibrary: '返回游戏库',
    backSystems: '主机',
    consoleAction: '主机操作',
    chooseSystem: '选择您的主机',
    available: '可用',
    comingSoon: '即将推出',
    close: '关闭',
    connected: '已连接',
    confirmSystem: '进入主机',
    formats: '格式',
    generationEightBit: '8 位家用世代',
    generationHandheld: '掌机世代',
    generationSixteenBit: '16 位家用世代',
    generationThreeD: '早期 3D 世代',
    disconnected: '设备已断开',
    emptyAction: '选择本地 ROM',
    emptyBody: '添加您自己的 .gb 或 .gbc 文件。游戏库仅保存在此电脑上。',
    emptyTitle: '您的游戏档案已准备好',
    errorTitle: '操作被中断',
    favorites: '收藏',
    favoriteGame: '收藏',
    feedbackSounds: '反馈音效',
    gameControls: '游戏控制',
    importError: '无法导入游戏。',
    inputSettings: '输入设置',
    mappingAssigned: '已分配',
    mappingCancelled: '更改已取消。',
    mappingCancel: '取消',
    mappingConfirm: '确认',
    mappingChooseDevice: '选择设备，然后确认以配置按键。',
    mappingEditButton: '选择主机按键并确认以编辑。',
    mappingPreview: '已捕获输入。确认保存，或返回取消。',
    mappingPressInput: '按下键盘按键或控制器按钮。',
    mappingSaved: '映射已保存。',
    interfaceAudio: '界面音频',
    interfaceLanguage: '界面语言',
    language: '语言',
    library: '游戏库',
    emptyCategory: '这里还没有内容',
    loading: '正在恢复游戏档案…',
    localPrivate: '原始本地文件 · 隐私优先',
    muteUiSounds: '静音界面音效',
    muted: '已静音',
    nowPlaying: '正在游戏',
    nextSystem: '下一台主机',
    pause: '暂停',
    play: '开始游戏',
    playerOneDevice: '玩家一设备',
    ready: '就绪',
    readyToPlay: '准备开始',
    previousSystem: '上一台主机',
    recent: '最近玩过',
    removeFavorite: '取消收藏',
    resume: '继续',
    saveStates: '即时存档',
    saveSlot: '存档位 {{number}}',
    emptySlot: '空',
    saveState: '保存',
    loadState: '读取',
    search: '搜索游戏库',
    sessionReady: '准备就绪',
    exitApplication: '退出 PixelCore',
    continuePlaying: '继续游戏',
    exitQuestion: '退出这个游戏？',
    exitToLibrary: '退出到游戏库',
    settings: '设置',
    settingsAdjustHint: '调整',
    settingsCloseHint: '返回',
    settingsConfirmHint: '确认',
    settingsMoveHint: '导航',
    soundsOn: '开启',
    playHint: '再次确认即可开始',
    globalSettings: 'PixelCore 设置',
    systemPosition: '第 {{current}} 台，共 {{total}} 台',
    systems: '选择主机',
    unavailableSystem: '{{name}} 即将推出。',
    statusPaused: '已暂停',
    statusRunning: '游戏运行中',
    statusStarting: '正在启动',
    stop: '退出游戏',
    tryAgain: '重试',
    preferencesWarningTitle: '偏好设置未保存',
    preferencesWarningMessage: '更改仍然有效，但无法保存。',
    volume: '音量',
  },
};

export const OFFICIAL_CATALOGS = { 'en-US': en, 'pt-BR': pt, 'zh-CN': zh } as const;
void i18n.use(initReactI18next).init({
  fallbackLng: 'en-US',
  interpolation: { escapeValue: true },
  lng: resolveLocale(undefined, typeof navigator === 'undefined' ? 'en-US' : navigator.language),
  resources: OFFICIAL_CATALOGS,
});

export const setLocale = async (locale: SupportedLocale): Promise<void> => {
  await i18n.changeLanguage(locale);
  if (typeof document !== 'undefined') document.documentElement.lang = locale;
};

export default i18n;
