import { constants } from 'node:fs';
import { access, mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

import { PluginManifestSchema } from '@platform/plugin-sdk';

export const PLUGIN_SCAFFOLD_TYPES = ['console', 'controller', 'game-metadata'] as const;
export type PluginScaffoldType = (typeof PLUGIN_SCAFFOLD_TYPES)[number];

export interface CreatePluginScaffoldOptions {
  readonly cwd?: string;
  readonly id: string;
  readonly name: string;
  readonly output: string;
  readonly type: PluginScaffoldType;
}

export interface CreatedPluginScaffold {
  readonly directory: string;
  readonly files: readonly string[];
}

interface Template {
  readonly capabilities: readonly string[];
  readonly definition: string;
  readonly exportName: string;
  readonly sdk: string;
}

const templates: Readonly<Record<PluginScaffoldType, (id: string, name: string) => Template>> = {
  console: (id, name) => ({
    capabilities: ['cartridge-playback'],
    definition: `import { defineConsole } from '@platform/console-sdk';

export const plugin = defineConsole({
  console: {
    capabilities: ['cartridge-playback'],
    id: ${JSON.stringify(id)},
    inputActions: [{ id: 'action' }],
    inputMapping: {
      entries: [{ consoleAction: 'action', normalizedAction: 'primary' }],
      playerPortId: 'player-one',
      version: 1,
    },
    playerPorts: [{ id: 'player-one', inputActions: ['action'] }],
    supportedRomExtensions: ['.demo'],
  },
  manifest: ${manifestLiteral(id, name, 'console', ['cartridge-playback'])},
});
`,
    exportName: 'console',
    sdk: '@platform/console-sdk',
  }),
  controller: (id, name) => ({
    capabilities: ['gamepad-mapping'],
    definition: `import { defineController } from '@platform/controller-sdk';

export const plugin = defineController({
  controller: {
    id: ${JSON.stringify(id)},
    mappings: [{ input: { index: 0, kind: 'button' }, normalizedAction: 'primary' }],
    match: [{ standardMapping: true }],
  },
  manifest: ${manifestLiteral(id, name, 'controller', ['gamepad-mapping'])},
});
`,
    exportName: 'controller',
    sdk: '@platform/controller-sdk',
  }),
  'game-metadata': (id, name) => ({
    capabilities: ['localized-game-metadata'],
    definition: `import { defineGameMetadata } from '@platform/game-sdk';

export const plugin = defineGameMetadata({
  manifest: ${manifestLiteral(id, name, 'game-metadata', ['localized-game-metadata'])},
  metadata: {
    defaultLocale: 'en-US',
    id: ${JSON.stringify(id)},
    records: [{
      consoleId: 'org.example.console',
      id: 'example-game',
      provenance: { license: 'CC0-1.0', source: 'Replace with your source' },
      text: { 'en-US': { title: 'Example Game' } },
    }],
  },
});
`,
    exportName: 'game metadata',
    sdk: '@platform/game-sdk',
  }),
};

function manifestLiteral(
  id: string,
  name: string,
  type: PluginScaffoldType,
  capabilities: readonly string[],
): string {
  return JSON.stringify({
    apiVersion: 1,
    capabilities,
    id,
    name,
    permissions: [],
    type,
    version: '0.1.0',
  }, null, 2).replaceAll('\n', '\n  ');
}

const packageName = (id: string): string => `@plugin/${id.replaceAll('.', '-').replace(/^org-/, '')}`;

const contractTest = (typeLabel: string): string => `import { expect, test } from 'vitest';
import { validatePluginContract } from '@platform/plugin-test';

import { plugin } from './index.js';

test('satisfies the public ${typeLabel} plugin contract', () => {
  expect(validatePluginContract(plugin)).toMatchObject({ status: 'valid' });
});
`;

const readme = (name: string, type: PluginScaffoldType): string => `# ${name}

PixelCore ${type} plugin generated by \`@platform/plugin-cli\`.

## Development

Replace the reference values in \`src/index.ts\`, keep the manifest and definition IDs
aligned, and document capabilities, permissions, compatibility, and attribution.

Run \`pnpm test\` before opening a pull request. Do not import Electron, host internals,
or concrete plugins.
`;

const tsconfig = `{
  "extends": "../../../tsconfig.base.json",
  "compilerOptions": { "rootDir": "src" },
  "include": ["src/**/*.ts"]
}
`;

const tsconfigBuild = `{
  "extends": "./tsconfig.json",
  "compilerOptions": { "noEmit": false, "outDir": "dist", "tsBuildInfoFile": "dist/.tsbuildinfo" }
}
`;

const ensureAbsent = async (path: string): Promise<void> => {
  try {
    await access(path, constants.F_OK);
    throw new Error(`Refusing to overwrite existing path: ${path}`);
  } catch (error) {
    if (error instanceof Error && error.message.startsWith('Refusing to overwrite')) throw error;
  }
};

export const createPluginScaffold = async (
  options: CreatePluginScaffoldOptions,
): Promise<CreatedPluginScaffold> => {
  if (!PLUGIN_SCAFFOLD_TYPES.includes(options.type))
    throw new Error(`Unsupported scaffold type: ${String(options.type)}`);
  if (options.name.trim().length === 0) throw new Error('Plugin name must not be empty.');

  const template = templates[options.type](options.id, options.name.trim());
  const manifest = {
    apiVersion: 1,
    capabilities: template.capabilities,
    id: options.id,
    name: options.name.trim(),
    permissions: [],
    type: options.type,
    version: '0.1.0',
  };
  const manifestResult = PluginManifestSchema.safeParse(manifest);
  if (!manifestResult.success)
    throw new Error(`Invalid plugin identity: ${manifestResult.error.issues.map(({ message }) => message).join(' ')}`);

  const directory = resolve(options.cwd ?? process.cwd(), options.output);
  await ensureAbsent(directory);

  const packageJson = {
    name: packageName(options.id),
    version: '0.1.0',
    private: true,
    type: 'module',
    exports: { '.': { types: './dist/index.d.ts', default: './dist/index.js' } },
    files: ['dist', 'manifest.json'],
    scripts: {
      build: 'tsc -p tsconfig.build.json',
      lint: 'eslint src --max-warnings=0',
      test: 'vitest run',
      typecheck: 'tsc -p tsconfig.json --noEmit',
    },
    dependencies: { [template.sdk]: 'workspace:*' },
    devDependencies: { '@platform/plugin-test': 'workspace:*' },
  };
  const files: Readonly<Record<string, string>> = {
    'README.md': readme(options.name.trim(), options.type),
    'manifest.json': `${JSON.stringify(manifestResult.data, null, 2)}\n`,
    'package.json': `${JSON.stringify(packageJson, null, 2)}\n`,
    'src/contract.test.ts': contractTest(template.exportName),
    'src/index.ts': template.definition,
    'tsconfig.build.json': tsconfigBuild,
    'tsconfig.json': tsconfig,
  };

  await Promise.all(Object.keys(files).map((file) => mkdir(dirname(resolve(directory, file)), { recursive: true })));
  await Promise.all(Object.entries(files).map(([file, contents]) => writeFile(resolve(directory, file), contents, { encoding: 'utf8', flag: 'wx' })));
  return { directory, files: Object.keys(files).sort() };
};
